# Generated by Django 3.2.5 on 2023-07-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('QB', 'QuarterBack'), ('RB', 'RunningBack'), ('WR', 'WideReceiver'), ('TE', 'TightEnd'), ('DEF', 'Defense'), ('K', 'Kicker')], max_length=3)),
                ('team', models.CharField(choices=[('ARZ', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houson Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LV', 'Las Vegas Raiders'), ('LAC', 'Los Angeles Chargers'), ('LAR', 'Los Angeles Rams'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SF', 'San Francisco 49ers'), ('SEA', 'Seattle Seahawks'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Commanders')], max_length=3)),
                ('bye_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RankingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_src_name', models.CharField(max_length=30)),
                ('scoring_type', models.CharField(choices=[('STANDARD', 'STANDARD'), ('HALF_PPR', 'HALF_PPR'), ('PPR', 'PPR')], max_length=10)),
                ('players_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking_app.player')),
                ('ranking_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking_app.rankingsource')),
            ],
        ),
    ]
