# Generated by Django 3.2.5 on 2023-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsource',
            name='ranking_src_url',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rankingsource',
            name='scoring_type',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('PPR', 'PPR')], max_length=10),
        ),
    ]
