# Generated by Django 3.2.5 on 2023-07-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_app', '0005_rankingsource_position_ranking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingsource',
            name='players_count',
        ),
    ]
